# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:  
- task: AzureAppConfigurationPush@3
  inputs:
    azureSubscription: 'testConnection'
    AppConfigurationEndpoint: 'https://appconfigimporttest.azconfig.io'
    ConfigurationFile: './appsetting.json'
    Separator: ':'
    Prefix: 'PRD'
    Strict: false