# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'
variables:
  solution: 'SampleWebApplication/SampleWebApplication.sln'
  binPath: 'SampleWebApplication/bin/release/net6.0'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: builder
  jobs: 
  - job: putAppConfiguration
    steps:  
    - task: AzureAppConfigurationPush@3
      inputs:
        azureSubscription: 'testConnection'
        AppConfigurationEndpoint: 'https://appconfigimporttest.azconfig.io'
        ConfigurationFile: 'config/appconfig.json'
        Separator: ':'
        Prefix: 'PRD:'
        Label: 'Pushtest'
        Tags: '{"isTest": "true"}'
        Strict: false

  - job: buildApp
    # dependsOn: putAppConfiguration
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
    # - task: ArchiveFiles@2
    #   inputs:
    #     rootFolderOrFile: '$(binPath)'
    #     includeRootFolder: true
    #     archiveType: 'zip'
    #     archiveFile: '$(binPath)/$(Build.BuildId).zip'
    #     replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/SampleWebApplication.zip'
        artifact: 'app'
        publishLocation: 'pipeline'

- stage: validationA
  dependsOn: builder
  jobs:
  - job: validationA
    pool: Server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'kurunin52@gmail.com'
        onTimeout: 'resume'

- stage: validationB
  dependsOn: builder
  jobs:
  - job: validationB
    pool: Server
    steps:
    - task: ManualValidation@0
      inputs:
        notifyUsers: 'kurunin52@gmail.com'
        onTimeout: 'resume'

- stage: stageB
  dependsOn: [validationA, validationB]
  jobs: 
  - job: deployApp
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'app'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'testConnection'
        appType: 'webApp'
        WebAppName: 'kurunin52SampleWebApp'
        packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
